### ISSUE TITLE
support rem

### ISSUE THREAD

**Issue by mark-hahn** [oscarsolas/atom-px-to-ems#1]
IMHO, `rem` is a lot more useful them `em`.  Em has inheritance problems that `rem` doesn't.  So could there be a settings to use `rem` instead?

**Comment by oscarsolas** [comment]
Hi Mark, 

Thank you for your suggestion.
I have just updated the plugin, so in the latest version you can choose between <code>rem</code> and <code>em</code> units in the package configuration.

**Comment by mark-hahn** [comment]
thanks
