### ISSUE TITLE
shortcut not working on windows

### ISSUE THREAD

**Issue by davidspiess** [oscarsolas/atom-px-to-ems#2]
Add something like this in `px-to-em.cson`

``` coffescript
'.platform-win32 atom-workspace':
  'ctrl-shift-e': 'px-to-em:toggle'
```

**Comment by oscarsolas** [comment]
Thank you for your suggestion, davidspiess. This feature has been updated in the latest version of the plugin

**Comment by davidspiess** [comment]
Awesome! :)
